### ISSUE TITLE
Inverted relation between Decodable and RelationDecodable

### ISSUE THREAD

**Issue by AljoschaMeyer** [earthstar-project/willow-rs#60]
Currently, RelationDecodable is a subtrait of Decodable. It should be the other way around, however: every encoding function is also an encoding relation, but an encoding relation is not necessarily an encoding function.

The willow spec should probably introduce them in the other order for the same reason. I'm sure we'll get to that eventually...

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the trait hierarchy to make Decodable a subtrait of RelationDecodable in both traits.rs and traits_sync.rs. This change reflects that every encoding function is also an encoding relation, but not vice versa. Updated trait definitions and implementations accordingly.

You can review changes in this commit: https://github.com/lkilu6456546/earthstar-project-willow-rs-60/commit/2d7ee47653e517c5a184c733c5dac81b5b116e9f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
